# Generated by Django 5.2.6 on 2025-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
